In [1]:
import pandas as pd
from konlpy.tag import Okt
df = pd.read_csv('data/allergy_search.csv')

In [ ]:
df

In [5]:
import pandas as pd
from konlpy.tag import Okt

datas = df['allergy2']

# allergy_dict 미리 정의
allergy_dict = {1: ['알류', '계란', '달걀', '난류','메추리알','메추리','추리알','난각','날류','난백','난황','난각','게란'], 
                2: ['우유','유우', '탈지분유','유유','분유','유청','카제인','우류'], 
                3: '메밀', 
                4: ['땅콩', '탕콩'],
                5: ['대두','두부','대듀','콩','적두','유부'], 
                6: ['밀','밀가루'], 
                7: '고등어', 
                8: '게', 
                9: ['새우'], 
                10: ['돼지고기','괘지','괘지고기','돈','돼지','돼고기','돈창', '돈혈', '돈지방','괘'],
                11: ['복숭아'], 
                12: ['토마토', '토마투','토마도','토마','토미토'],
                13: ['아황산', '아황산나트륨', '이황산', '이산화', '아산화', '이산화황','아산화황','이산화항','이황산류'],
                14: ['호두','피칸','호도'], 
                15: ['닭고기', '계육','닭','닭괴'], 
                16: ['쇠고기', '우육', '소고기', '소뼈','쇠구기'], 
                17: ['오징어', '오지엉','오지','지엉'],
                18: ['조개류','굴','홍합','조개','백합','바지락'], 
                19: '잣',
                20: ['아몬드','페닐알라닌','헤이즐넛','참깨']}

allergy_nums = []
for data in datas:
    data = str(data)
    okt = Okt()
    words = okt.pos(data)
    allergy_columns = []

    for word, tag in words:
        if tag == 'Noun':
            for allergy_key, allergy_value in allergy_dict.items():
                if isinstance(allergy_value, list):
                    if word in allergy_value:
                        allergy_columns.append(allergy_key)
                        break
                else:
                    if word == allergy_value:
                        allergy_columns.append(allergy_key)
                        break
        
    allergy_num = ','.join(str(x) for x in allergy_columns) # 문자열로 변환
    allergy_nums.append(allergy_num)

df['allergy_num'] = allergy_nums # DataFrame에 열 추가
print(df)

       Unnamed: 0   rnum                                            rawmtrl  \
0               0      1  찹쌀,김,참깨,옥수수기름(옥배유),양파,무,대파,천일염,마늘,새우,멸치,다시마,건표...
1               1      2  찹쌀,김,참깨,옥수수기름(옥배유),아몬드,양파,무,천일염,대파,마늘,새우,멸치,다시...
2               2      3  찹쌀,김,참깨,옥수수기름(옥배유),양파,무,대파,천일염,마늘,새우,멸치,다시마,건표...
3               3      4                                               군고구마
4               4      5                                               군고구마
...           ...    ...                                                ...
15087       15087  15088  된장63.15%[대두{수입산(미국산,중국산,캐나다산)},소맥분(밀:미국산,호주산),...
15088       15088  15089  물엿,소맥분(밀:미국산,호주산),혼합양념(중국산)[고춧가루6.12%,(고추:중국산)...
15089       15089  15090  탈지대두[수입산(인도산,미국산,중국산)],정제수,양조간장원액(대만산)[탈지대두,소맥...
15090       15090  15091  정제수,아미노산액[탈지대두:외국산(인도산,미국산,중국산등)],정제소금(국산),액상과...
15091       15091  15092  물엿, 소맥분(밀:미국산,호주산),혼합양념(중국산)[고춧가루6.12%(고추:중국산)...

      allergy allergy2 allergy_1 allergy_2 allergy_3 allergy_4 allergy_5  ...  \
0          없음       없음        없음       NaN       NaN       NaN       NaN  ...
1         아몬드      아몬드       아몬드       NaN       NaN       NaN       NaN  ...
2          없음       없음        없음       NaN       NaN       NaN       NaN  ...
3          없음       없음        없음       NaN       NaN       NaN       NaN  ...
4          없음       없음        없음       NaN       NaN       NaN       NaN  ...
...       ...      ...       ...       ...       ...       ...       ...  ...
15087    대두,밀     대두,밀        대두         밀       NaN       NaN       NaN  ...
15088       밀        밀         밀       NaN       NaN       NaN       NaN  ...
15089    대두,밀     대두,밀        대두         밀       NaN       NaN       NaN  ...
15090    대두,밀     대두,밀        대두         밀       NaN       NaN       NaN  ...
15091    알수없음     알수없음      알수없음       NaN       NaN       NaN       NaN  ...

      allergy_13 allergy_14 allergy_15 allergy_16 allergy_17 allergy_18  \
0            NaN        NaN        NaN        NaN        NaN        NaN
1            NaN        NaN        NaN        NaN        NaN        NaN
2            NaN        NaN        NaN        NaN        NaN        NaN
3            NaN        NaN        NaN        NaN        NaN        NaN
4            NaN        NaN        NaN        NaN        NaN        NaN
...          ...        ...        ...        ...        ...        ...
15087        NaN        NaN        NaN        NaN        NaN        NaN
15088        NaN        NaN        NaN        NaN        NaN        NaN
15089        NaN        NaN        NaN        NaN        NaN        NaN
15090        NaN        NaN        NaN        NaN        NaN        NaN
15091        NaN        NaN        NaN        NaN        NaN        NaN

      allergy_19 allergy_20 allergy_num2 allergy_num
0            NaN        NaN         20,9
1            NaN        NaN      20,20,9          20
2            NaN        NaN         20,9
3            NaN        NaN
4            NaN        NaN
...          ...        ...          ...         ...
15087        NaN        NaN        5,6,6         5,6
15088        NaN        NaN          6,6           6
15089        NaN        NaN        5,5,6         5,6
15090        NaN        NaN        5,5,6         5,6
15091        NaN        NaN          6,6

[15092 rows x 27 columns]

In [ ]:
df2 = df[['allergy2', 'allergy_num']]
df2.sample(20)
#검증 --> , 로 구분되는 개체들의 수가 동일하면 true, 아니면 false 반환
df2['match'] = df2.apply(lambda x: len(x['allergy2'].split(',')) == len(x['allergy_num'].split(',')), axis=1)
df2[df2['match'] == False].sample(50)

In [3]:
import pandas as pd
from konlpy.tag import Okt


datas = df['rawmtrl']

# allergy_dict 미리 정의
allergy_dict = {1: ['알류', '계란', '달걀', '난류','메추리알','메추리','추리알','난각','날류','난백','난황','난각','게란'], 
                2: ['우유','유우', '탈지분유','유유','분유','유청','카제인','우류'], 
                3: '메밀', 
                4: ['땅콩', '탕콩'],
                5: ['대두','두부','대듀','콩','적두','유부'], 
                6: ['밀','밀가루'], 
                7: '고등어', 
                8: '게', 
                9: ['새우'], 
                10: ['돼지고기','괘지','괘지고기','돈','돼지','돼고기','돈창', '돈혈', '돈지방','괘'],
                11: ['복숭아'], 
                12: ['토마토', '토마투','토마도','토마','토미토'],
                13: ['아황산', '아황산나트륨', '이황산', '이산화', '아산화', '이산화황','아산화황','이산화항','이황산류'],
                14: ['호두','피칸','호도'], 
                15: ['닭고기', '계육','닭','닭괴'], 
                16: ['쇠고기', '우육', '소고기', '소뼈','쇠구기'], 
                17: ['오징어', '오지엉','오지','지엉'],
                18: ['조개류','굴','홍합','조개','백합','바지락'], 
                19: '잣',
                20: ['아몬드','페닐알라닌','헤이즐넛','참깨']}

allergy_nums = []
for data in datas:
    data = str(data)
    okt = Okt()
    words = okt.pos(data)
    allergy_columns = []

    for word, tag in words:
        if tag == 'Noun':
            for allergy_key, allergy_value in allergy_dict.items():
                if isinstance(allergy_value, list):
                    if word in allergy_value:
                        allergy_columns.append(allergy_key)
                        break
                else:
                    if word == allergy_value:
                        allergy_columns.append(allergy_key)
                        break
        
    allergy_num = ','.join(str(x) for x in allergy_columns) # 문자열로 변환
    allergy_nums.append(allergy_num)

df['allergy_num2'] = allergy_nums # DataFrame에 열 추가
print(df)

       Unnamed: 0   rnum                                            rawmtrl  \
0               0      1  찹쌀,김,참깨,옥수수기름(옥배유),양파,무,대파,천일염,마늘,새우,멸치,다시마,건표...
1               1      2  찹쌀,김,참깨,옥수수기름(옥배유),아몬드,양파,무,천일염,대파,마늘,새우,멸치,다시...
2               2      3  찹쌀,김,참깨,옥수수기름(옥배유),양파,무,대파,천일염,마늘,새우,멸치,다시마,건표...
3               3      4                                               군고구마
4               4      5                                               군고구마
...           ...    ...                                                ...
15087       15087  15088  된장63.15%[대두{수입산(미국산,중국산,캐나다산)},소맥분(밀:미국산,호주산),...
15088       15088  15089  물엿,소맥분(밀:미국산,호주산),혼합양념(중국산)[고춧가루6.12%,(고추:중국산)...
15089       15089  15090  탈지대두[수입산(인도산,미국산,중국산)],정제수,양조간장원액(대만산)[탈지대두,소맥...
15090       15090  15091  정제수,아미노산액[탈지대두:외국산(인도산,미국산,중국산등)],정제소금(국산),액상과...
15091       15091  15092  물엿, 소맥분(밀:미국산,호주산),혼합양념(중국산)[고춧가루6.12%(고추:중국산)...

      allergy allergy2 allergy_1 allergy_2 allergy_3 allergy_4 allergy_5  ...  \
0          없음       없음        없음       NaN       NaN       NaN       NaN  ...
1         아몬드      아몬드       아몬드       NaN       NaN       NaN       NaN  ...
2          없음       없음        없음       NaN       NaN       NaN       NaN  ...
3          없음       없음        없음       NaN       NaN       NaN       NaN  ...
4          없음       없음        없음       NaN       NaN       NaN       NaN  ...
...       ...      ...       ...       ...       ...       ...       ...  ...
15087    대두,밀     대두,밀        대두         밀       NaN       NaN       NaN  ...
15088       밀        밀         밀       NaN       NaN       NaN       NaN  ...
15089    대두,밀     대두,밀        대두         밀       NaN       NaN       NaN  ...
15090    대두,밀     대두,밀        대두         밀       NaN       NaN       NaN  ...
15091    알수없음     알수없음      알수없음       NaN       NaN       NaN       NaN  ...

      allergy_12 allergy_13 allergy_14 allergy_15 allergy_16 allergy_17  \
0            NaN        NaN        NaN        NaN        NaN        NaN
1            NaN        NaN        NaN        NaN        NaN        NaN
2            NaN        NaN        NaN        NaN        NaN        NaN
3            NaN        NaN        NaN        NaN        NaN        NaN
4            NaN        NaN        NaN        NaN        NaN        NaN
...          ...        ...        ...        ...        ...        ...
15087        NaN        NaN        NaN        NaN        NaN        NaN
15088        NaN        NaN        NaN        NaN        NaN        NaN
15089        NaN        NaN        NaN        NaN        NaN        NaN
15090        NaN        NaN        NaN        NaN        NaN        NaN
15091        NaN        NaN        NaN        NaN        NaN        NaN

      allergy_18 allergy_19 allergy_20 allergy_num2
0            NaN        NaN        NaN         20,9
1            NaN        NaN        NaN      20,20,9
2            NaN        NaN        NaN         20,9
3            NaN        NaN        NaN
4            NaN        NaN        NaN
...          ...        ...        ...          ...
15087        NaN        NaN        NaN        5,6,6
15088        NaN        NaN        NaN          6,6
15089        NaN        NaN        NaN        5,5,6
15090        NaN        NaN        NaN        5,5,6
15091        NaN        NaN        NaN          6,6

[15092 rows x 26 columns]

In [25]:
df[['allergy_num2','allergy_num']].sample(30)

                allergy_num2    allergy_num
11789                                     6
12399  6,6,1,4,5,4,4,4,20,20
3222                16,16,16             16
8477                   2,2,2            5,2
1941
9935                10,5,6,6       10,5,6,9
3447                  5,15,5       5,6,2,15
4637
1036                       9        8,5,6,9
8290                    10,5
9631                    10,1  10,16,1,6,5,2
9386         6,6,2,1,2,2,2,5        6,2,1,5
4105
10704         5,5,5,20,14,19
12006            2,2,5,5,5,6
12460                    6,6
6057                       5
9220
8236       10,16,10,16,7,5,6
8988                      15         15,2,5
8095
14833             15,15,10,5    10,15,5,2,6
9409       6,6,1,2,2,6,5,6,6
3115                    10,5
5836               2,2,6,2,2              2
3802                16,16,16         5,6,16
5256        15,18,18,18,18,8      15,5,6,18
2441                       6
4693
4570                       5              5

In [ ]:
df = pd.read_csv('data/allergy_search.csv')
datas = df['allergy_1']

for data in datas:
    data = str(data)
    okt = Okt()
    words = okt.pos(data)
    allergy_columns = []

    # try: 
    for word, tag in words:
        if tag == 'Noun':
            for allergy_key, allergy_value in allergy_dict.items():
                if isinstance(allergy_value, list):
                    if word in allergy_value:
                        allergy_columns.append(allergy_key)
                        break
                else:
                    if word == allergy_value:
                        allergy_columns.append(allergy_key)
                        break
    # except:
    #     pass
    #     print(f'{data}오류')
        
    print(allergy_columns)